version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=password
      - MONGODB_INITDB_DATABASE=smarties
    volumes:
      - mongodb_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all

volumes:
  mongodb_data:
